/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectsample;

import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class game extends javax.swing.JFrame {
   int count=0;

    /**
     * Creates new form game
     */
    public game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f1 = new javax.swing.JFrame();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        f1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("jButton2");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        f1.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 210, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsample/images/2.jpg"))); // NOI18N
        f1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L2.setBackground(new java.awt.Color(255, 255, 102));
        L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsample/images/yello.jpg"))); // NOI18N
        L2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 100, 100));

        L1.setBackground(new java.awt.Color(255, 255, 102));
        L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsample/images/yello.jpg"))); // NOI18N
        L1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L1MouseClicked(evt);
            }
        });
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 100, 100));

        L5.setBackground(new java.awt.Color(255, 255, 102));
        L5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsample/images/yello.jpg"))); // NOI18N
        L5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 100, 100));

        L3.setBackground(new java.awt.Color(255, 255, 102));
        L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsample/images/yello.jpg"))); // NOI18N
        L3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 100, 100));

        L6.setBackground(new java.awt.Color(255, 255, 102));
        L6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsample/images/yello.jpg"))); // NOI18N
        L6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 100, 100));

        L4.setBackground(new java.awt.Color(255, 255, 102));
        L4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsample/images/yello.jpg"))); // NOI18N
        L4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 100, 100));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 213, -1, -1));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 93, 39));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseClicked
        System.out.println("");
if(L1.isEnabled()&&count==0){
    L1.setIcon(new ImageIcon("C:\\ishita\\level1\\1.jpg"));
}
else if(L1.isEnabled()){
    L1.setEnabled(false);
    L1.setIcon(new ImageIcon("C:\\ishita\\level1\\yello.jpg"));
}
else if(L3.isEnabled()&&count==1){
    L1.setVisible(false);
    L3.setVisible(false);
}
else if (count==1){
    L1.setEnabled(true);
    L1.setIcon(new ImageIcon("C:\\ishita\\level1\\1.jpg"));
    L2.setEnabled(false);
    L3.setEnabled(false);
    L4.setEnabled(false);
    L5.setEnabled(false);
    L6.setEnabled(false);
}
else{
    L1.setEnabled(true);L1.setIcon(new ImageIcon("C:\\ishita\\level1\\1.jpg"));
}

// TODO add your handling code here:
    }//GEN-LAST:event_L1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
f1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JFrame f1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
