/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectsample;

/**
 *
 * @author dell 3542
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell 3542\\Desktop\\ishita\\egg basket\\images.jpg")); // NOI18N
        l1.setText("jLabel1");
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 54, 24));

        l2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell 3542\\Desktop\\ishita\\egg basket\\images.jpg")); // NOI18N
        l2.setText("jLabel2");
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 54, 24));

        l3.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell 3542\\Desktop\\ishita\\egg basket\\images.jpg")); // NOI18N
        l3.setText("jLabel3");
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 54, 24));

        l4.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell 3542\\Desktop\\ishita\\egg basket\\images.jpg")); // NOI18N
        l4.setText("jLabel4");
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 54, 24));

        l5.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell 3542\\Desktop\\ishita\\egg basket\\images.jpg")); // NOI18N
        l5.setText("jLabel5");
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 50, 24));

        l6.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell 3542\\Desktop\\ishita\\egg basket\\images.jpg")); // NOI18N
        l6.setText("jLabel6");
        jPanel1.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 54, 24));

        l7.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell 3542\\Desktop\\ishita\\egg basket\\images.jpg")); // NOI18N
        l7.setText("jLabel7");
        jPanel1.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 54, 24));

        l8.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell 3542\\Desktop\\ishita\\egg basket\\images.jpg")); // NOI18N
        l8.setText("jLabel8");
        jPanel1.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 54, 24));

        l9.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell 3542\\Desktop\\ishita\\egg basket\\images.jpg")); // NOI18N
        l9.setText("jLabel9");
        jPanel1.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 58, 24));

        l10.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell 3542\\Desktop\\ishita\\egg basket\\images.jpg")); // NOI18N
        l10.setText("jLabel10");
        jPanel1.add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 54, 24));

        jButton1.setText("left");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        jButton2.setText("right");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean b1=l1.isVisible();
        boolean b2=l2.isVisible();
        boolean b3=l3.isVisible();
        boolean b4=l4.isVisible();
        boolean b5=l5.isVisible();
        boolean b6=l6.isVisible();
        boolean b7=l7.isVisible();
        boolean b8=l8.isVisible();
        boolean b9=l9.isVisible();
        boolean b10=l10.isVisible();

        if(b1==true){
            l1.setVisible(false);
            l10.setVisible(true);}
        else if(b2==true){
            l2.setVisible(false);
            l1.setVisible(true);}
        else if(b3==true){
            l3.setVisible(false);
            l2.setVisible(true);}
        else if(b4==true){
            l4.setVisible(false);
            l3.setVisible(true);}
        else if(b5==true){
            l5.setVisible(false);
            l4.setVisible(true);}
        else if(b6==true){
            l6.setVisible(false);
            l5.setVisible(true);}
        else if(b7==true){
            l7.setVisible(false);
            l6.setVisible(true);}
        else if(b8==true){
            l8.setVisible(false);
            l7.setVisible(true);}
        else if(b9==true){
            l9.setVisible(false);
            l8.setVisible(true);}
        else if(b10==true){
            l10.setVisible(false);
            l9.setVisible(true);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean b1=l1.isVisible();
        boolean b2=l2.isVisible();
        boolean b3=l3.isVisible();
        boolean b4=l4.isVisible();
        boolean b5=l5.isVisible();
        boolean b6=l6.isVisible();
        boolean b7=l7.isVisible();
        boolean b8=l8.isVisible();
        boolean b9=l9.isVisible();
        boolean b10=l10.isVisible();

        if(b1==true){
            l1.setVisible(false);
            l2.setVisible(true);}
        else if(b2==true){
            l2.setVisible(false);
            l3.setVisible(true);}
        else if(b3==true){
            l3.setVisible(false);
            l4.setVisible(true);}
        else if(b4==true){
            l4.setVisible(false);
            l5.setVisible(true);}
        else if(b5==true){
            l5.setVisible(false);
            l6.setVisible(true);}
        else if(b6==true){
            l6.setVisible(false);
            l7.setVisible(true);}
        else if(b7==true){
            l7.setVisible(false);
            l8.setVisible(true);}
        else if(b8==true){
            l8.setVisible(false);
            l9.setVisible(true);}
        else if(b9==true){
            l9.setVisible(false);
            l10.setVisible(true);}
        else if(b10==true){
            l10.setVisible(false);
            l1.setVisible(true);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
l1.setVisible(true);  
l2.setVisible(false); 
l3.setVisible(false); 
l4.setVisible(false); 
l5.setVisible(false); 
l6.setVisible(false);
l7.setVisible(false); 
l8.setVisible(false); 
l9.setVisible(false); 
l10.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
